"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const clientController_1 = require("../controllers/clientController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.post("/", clientController_1.createClient);
router.get("/", clientController_1.getClients);
router.get("/:id", clientController_1.getClient);
router.patch("/:id", clientController_1.updateClient);
exports.default = router;
