"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const reportController_1 = require("../controllers/reportController");
const reportController_2 = require("../controllers/reportController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.get("/summary", reportController_1.getSummary);
router.get("/top-places", reportController_1.getTopPlaces);
router.get("/utilization/:placeId", reportController_1.getSlotUtilization);
router.get("/active-places", reportController_2.getActivePlacesCount);
exports.default = router;
