"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const slotController_1 = require("../controllers/slotController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.post("/", slotController_1.createSlot);
router.get("/:placeId", slotController_1.getSlotsByPlace);
router.patch("/:id", slotController_1.updateSlot);
router.post("/:id/cancel", slotController_1.cancelSlot);
exports.default = router;
